
x="`cygpath -u "C:\Program Files\OpenNI2\Redist\OpenNI2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\libjpeg-turbo64\bin\jpeg62.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\Azure Kinect SDK v1.4.1\sdk\windows-desktop\amd64\release\bin\k4a.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\Azure Kinect Body Tracking SDK\tools\k4abt.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\Azure Kinect SDK v1.4.1\sdk\windows-desktop\amd64\release\bin\k4arecord.dll"`" ; cp "$x" .
x="`cygpath -u "C:\opencv\build\x64\vc15\bin\opencv_world455.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\bin\pcl_common.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\bin\pcl_io.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\bin\pcl_io_ply.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files (x86)\Intel RealSense SDK 2.0\bin\x64\realsense2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonCore-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonDataModel-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonExecutionModel-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonMath-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonMisc-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonSystem-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonTransforms-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkDICOMParser-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOCore-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOGeometry-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOImage-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOLegacy-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOPLY-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkImagingCore-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkdoubleconversion-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkjpeg-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtklz4-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtklzma-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkmetaio-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkpng-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtksys-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtktiff-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkzlib-8.2.dll"`" ; cp "$x" .

x="`cygpath -u "C:\Program Files\OpenNI2\Redist\OpenNI2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\libjpeg-turbo64\bin\jpeg62.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\Azure Kinect SDK v1.4.1\sdk\windows-desktop\amd64\release\bin\k4a.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\Azure Kinect Body Tracking SDK\tools\k4abt.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\Azure Kinect SDK v1.4.1\sdk\windows-desktop\amd64\release\bin\k4arecord.dll"`" ; cp "$x" .
x="`cygpath -u "C:\opencv\build\x64\vc15\bin\opencv_world455.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\bin\pcl_common.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\bin\pcl_io.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\bin\pcl_io_ply.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files (x86)\Intel RealSense SDK 2.0\bin\x64\realsense2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonCore-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonDataModel-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonExecutionModel-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonMath-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonMisc-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonSystem-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonTransforms-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkDICOMParser-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOCore-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOGeometry-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOImage-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOLegacy-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOPLY-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkImagingCore-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkdoubleconversion-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkjpeg-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtklz4-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtklzma-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkmetaio-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkpng-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtksys-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtktiff-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkzlib-8.2.dll"`" ; cp "$x" .

x="`cygpath -u "C:\Program Files\OpenNI2\Redist\OpenNI2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\libjpeg-turbo64\bin\jpeg62.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\Azure Kinect SDK v1.4.1\sdk\windows-desktop\amd64\release\bin\k4a.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\Azure Kinect Body Tracking SDK\tools\k4abt.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\Azure Kinect SDK v1.4.1\sdk\windows-desktop\amd64\release\bin\k4arecord.dll"`" ; cp "$x" .
x="`cygpath -u "C:\opencv\build\x64\vc15\bin\opencv_world455.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\bin\pcl_common.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\bin\pcl_io.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\bin\pcl_io_ply.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files (x86)\Intel RealSense SDK 2.0\bin\x64\realsense2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonCore-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonDataModel-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonExecutionModel-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonMath-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonMisc-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonSystem-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkCommonTransforms-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkDICOMParser-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOCore-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOGeometry-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOImage-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOLegacy-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkIOPLY-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkImagingCore-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkdoubleconversion-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkjpeg-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtklz4-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtklzma-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkmetaio-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkpng-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtksys-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtktiff-8.2.dll"`" ; cp "$x" .
x="`cygpath -u "C:\Program Files\PCL 1.11.1\3rdParty\VTK\bin\vtkzlib-8.2.dll"`" ; cp "$x" .

